[package]
name = "rsed"
version = "0.1.0"
authors = ["Pablo Berganza <pberganza10@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.2"
regex = "1.3.1"
